[features]
seeds = false
skip-lint = false

[programs.localnet]
lottery = "H3nY6p687WVyxTtjumFaFFm8qqnLL6LGR72TBCHDLaL3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts" 